#afterbuild#version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mex_database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mex_database"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  data_ingestion:
    image: bhargavdeekshithvasu1997/mars_express_orbiter:data_ingestion
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mex_database
      DB_USER: admin
      DB_PASS: 1234
    volumes:
      - ./data:/app/data  # Mount the host data directory to /app/data in the container
      - flags_volume:/flags

  preprocessing:
    image: bhargavdeekshithvasu1997/mars_express_orbiter:preprocessing
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mex_database
      DB_USER: admin
      DB_PASS: 1234
    volumes:
      - flags_volume:/flags

  model_training:
    image: bhargavdeekshithvasu1997/mars_express_orbiter:model_training
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mex_database
      DB_USER: admin
      DB_PASS: 1234
    volumes:
      - ./models:/models  # To store the pickle files in the "models" folder
      - flags_volume:/flags

  model_testing:
    image: bhargavdeekshithvasu1997/mars_express_orbiter:model_testing
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mex_database
      DB_USER: admin
      DB_PASS: 1234
    volumes:
      - ./models:/models  # To access the pickle files and metadata.json
      - ./results:/results  # To store the predictions
      - flags_volume:/flags

volumes:
  db_data:
  flags_volume:

